// ELEC2645 Pong Game Demo
// =======================
// A classic Pong game demonstrating object-oriented game architecture with proper game loop.
// 
// KEY CONCEPTS:
// - Game objects (Ball, Paddle) encapsulate their own data and behavior
// - AABB (Axis-Aligned Bounding Box) collision detection for simple, fast collision checking
// - Update/Render separation: game logic updates happen separately from drawing
// - Game loop pattern: HANDLE INPUT → UPDATE OBJECTS → RENDER (full clear/redraw each frame)
//
// Controls:
// - Joystick UP/DOWN: Move paddle up and down
// - Objective: Hit ball with paddle to gain points
//
// Architecture:
// - PongEngine: Main game engine managing Ball, Paddle, and collisions
// - Ball: Object-oriented ball with position, velocity, and rendering
// - Paddle: Object-oriented paddle with input handling and collision
// - Utils: Collision detection (AABB) and shared types


// STM32 HAL headers (auto-generated by STM32CubeMX)
#include "main.h"
#include "tim.h"       // Timer 2 for PWM buzzer control
#include "usart.h"     // For serial output
#include "gpio.h"      // GPIO control
#include "adc.h"       // ADC for joystick input
#include "rng.h"       // RNG for randomized ball reset

// AUTO-GENERATED STM32 FUNCTION PROTOTYPES - DO NOT EDIT
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);

// Buzzer library
#include "Buzzer.h" // For buzzer control using TIM2
#include "PWM.h"    // For PWM control of the LED - not used in this demo but included for completeness and future expansion
#include "LCD.h"  // For LCD demonstration 
#include "Joystick.h" // include the Joystick driver functions
#include "CatEngine.h" // Cat petting game engine

#include <stdint.h>
#include <stdio.h>
#include <math.h>

// ===== BUZZER CONFIGURATION =====
// Configure buzzer to use TIM2 Channel 3 (current hardware setup)
Buzzer_cfg_t buzzer_cfg = {
    .htim = &htim2,
    .channel = TIM_CHANNEL_3,
    .tick_freq_hz = 1000000,  // 1MHz timer clock (prescaler = 79 with 80MHz input)
    .min_freq_hz = 20,
    .max_freq_hz = 20000,
    .setup_done = 0
};

// ===== LCD CONFIGURATION =====
ST7789V2_cfg_t cfg0 = {
    .setup_done = 0,
    .spi = SPI2,
    .RST = {.port = GPIOB, .pin = GPIO_PIN_2},
    .BL = {.port = GPIOB, .pin = GPIO_PIN_1},
    .DC = {.port = GPIOB, .pin = GPIO_PIN_11},
    .CS = {.port = GPIOB, .pin = GPIO_PIN_12},
    .MOSI = {.port = GPIOB, .pin = GPIO_PIN_15},
    .SCLK = {.port = GPIOB, .pin = GPIO_PIN_13},
    .dma = {.instance = DMA1, .channel = DMA1_Channel5}
};

// ===== JOYSTICK CONFIGURATION =====
Joystick_cfg_t joystick_cfg = {
    .adc = &hadc1,
    .x_channel = ADC_CHANNEL_1, //A5 on Nucleo board
    .y_channel = ADC_CHANNEL_2, //A4 on Nucleo board
    .sampling_time = ADC_SAMPLETIME_47CYCLES_5,
    .center_x = JOYSTICK_DEFAULT_CENTER_X,
    .center_y = JOYSTICK_DEFAULT_CENTER_Y,
    .deadzone = JOYSTICK_DEADZONE,
    .setup_done = 0
};

// Joystick data structure to hold readings
Joystick_t joystick_data;

// ===== PWM CONFIGURATION =====
// Configure PWM to use TIM4 Channel 1 (current hardware setup)
PWM_cfg_t pwm_cfg = {
    .htim = &htim4,
    .channel = TIM_CHANNEL_1,
    .tick_freq_hz = 1000000,  // 1MHz timer clock (prescaler = 79 with 80MHz input)
    .min_freq_hz = 10,
    .max_freq_hz = 50000,
    .setup_done = 0
};

// ===== FSM STATE DEFINITIONS =====
// For this Pong demo, we will not use a complex FSM with multiple states like the character demo.
// Instead, we will have a single "game running" state and a "game over" state. 
// The main game loop will run while the game is active, and when the player loses all lives, 
// it will transition to the game over state which displays the final score.

// ===== UTILITY FUNCTIONS =====

// Other utility functions (e.g. for collision detection) are defined in Utils.h

/**
 * @brief Redirect printf to UART for debugging
 */
int _write(int file, char *ptr, int len) {
    HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}

// ===== MENU & GAME SYSTEM =====
#include "Menu.h"
#include "InputHandler.h"
#include "Game_1.h"
#include "Game_2.h"
#include "Game_3.h"

MenuSystem menu;
MenuState current_state;

// ===== Main Function =====

int main(void)
{
    /* MCU Configuration */
    HAL_Init();
    SystemClock_Config();
    PeriphCommonClock_Config();

    /* Initialize peripherals */
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();
    MX_RNG_Init();

    // Initialize LCD first (this sets up GPIOB pins)
    LCD_init(&cfg0);

    // Initialize buzzer timer
    MX_TIM2_Init();
    buzzer_init(&buzzer_cfg);

    // Initialize TIM4 AFTER LCD to avoid GPIO conflict on PB6
    MX_TIM4_Init();

    // Initialize input, joystick, PWM
    Input_Init();
    Joystick_Init(&joystick_cfg);
    PWM_Init(&pwm_cfg);
    PWM_SetFreq(&pwm_cfg, 1000);
    PWM_SetDuty(&pwm_cfg, 0);
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);

    // Init menu
    Menu_Init(&menu);
    current_state = MENU_STATE_HOME;

    printf("Mekkineko initialized.\n");

    while (1) {
        switch (current_state) {
            case MENU_STATE_HOME:
                current_state = Menu_Run(&menu);
                break;
            case MENU_STATE_GAME_1:
                current_state = Game1_Run();
                break;
            case MENU_STATE_GAME_2:
                current_state = Game2_Run();
                break;
            case MENU_STATE_GAME_3:
                current_state = Game3_Run();
                break;
        }
    }
}

// ===== Interrupt Callback =====
// Note: Pong game only uses joystick input which is handled synchronously in the main loop.
// If button input is needed in the future, an interrupt handler can be added here.







// ==== AUTO-GENERATED STM32 FUNCTIONS ====
// DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING! 


/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 1;
  RCC_OscInitStruct.PLL.PLLN = 10;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief Peripherals Common Clock Configuration
  * @retval None
  */
void PeriphCommonClock_Config(void)
{
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /** Initializes the peripherals clock
  */
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_RNG|RCC_PERIPHCLK_ADC;
  PeriphClkInit.AdcClockSelection = RCC_ADCCLKSOURCE_PLLSAI1;
  PeriphClkInit.RngClockSelection = RCC_RNGCLKSOURCE_PLLSAI1;
  PeriphClkInit.PLLSAI1.PLLSAI1Source = RCC_PLLSOURCE_HSI;
  PeriphClkInit.PLLSAI1.PLLSAI1M = 1;
  PeriphClkInit.PLLSAI1.PLLSAI1N = 8;
  PeriphClkInit.PLLSAI1.PLLSAI1P = RCC_PLLP_DIV7;
  PeriphClkInit.PLLSAI1.PLLSAI1Q = RCC_PLLQ_DIV4;
  PeriphClkInit.PLLSAI1.PLLSAI1R = RCC_PLLR_DIV2;
  PeriphClkInit.PLLSAI1.PLLSAI1ClockOut = RCC_PLLSAI1_48M2CLK|RCC_PLLSAI1_ADC1CLK;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
}



/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
